#1. Go to source directory
cd src
#2. Run server
./server.py [hostname] <port>
#3. Run client
./client.py [hostname] <port> <path>

File will be recieveded from server and saved to directory "./recieved/"